# Root to save
root: /home/docker/Generated_Data/

# Type of element to generate
to_generate: f  #frame('f'), vector('v') or number('n')

# If toGenerate = 'n'; Function type
func_type: linear #linear, quadratic, sinusoidal, poly3, poly4

# If toGenerate = 'v'; Motion type, sample size
motion_type: sinusoidal #URM, linear, parabolic, sinusoidal
vector_len: 320

# If toGenerate = 'f'; Motion type (same in vector), height, width, object
height: 80
width: 120
object: point # point, circle
obj_color: 255 # For b/w: 255; For color: [0, 255, 0]
y0: fix # fix, var

circle_parameters:
  radius: 5

# Number of samples
n_samples: 10000

# Number of know points (x values)
n_points: 20

# Gap between last know and to predict samples
gap: 10

# Noise
noise:
  flag: False #True to add noise to the samples
  mean: 0
  stand_deviation: 50

# Separate train, test and validation
split:
  flag: True #True to separate
  fraction_test: 0.1
  fraction_validation: 0.1
