# Test dataset path
data_path: /home/docker/data_10/Frames_dataset/linear_point_255_fix_10000_80_120/linear_10_[None]_test

# Model path
model_path: /home/docker/Models/NOREC/Frames_dataset/linear_point_255_fix_500_80_120/simple/10_False_relu_categorical_crossentropy_10.h5