# Test dataset path
data_path: /home/docker/2017-tfm-nuria-oyaga/Frames_dataset/linear_point_255_var_5000/linear_10_[None]_test/samples
#data_path: /home/docker/2017-tfm-nuria-oyaga/Frames_dataset/linear_point_255_var_10000/linear_10_[None]_test/samples

# Model path
model_path: /home/docker/2017-tfm-nuria-oyaga/Models/...
