# Test dataset path
data_path: /home/docker/data_10/Frames_dataset/sinusoidal_point_255_var_1_100000_80_120/sinusoidal_10_[None]_test

# Model path
model_path: /home/docker/Models/REC/Frames_dataset/sinusoidal_point_255_var_1_100000_80_120/complex_convLSTM/10_False_relu_categorical_crossentropy_10.h5