# Version
version: 1

# Complexity: simple, complex, convLSTM
complexity: complex

# Root to save the model
root: /home/docker/Models/

# Type of the net to train (NoRec, Rec)
net_type: NoRec

# Activation function
activation: relu

# Loss function
func_loss: mean_squared_error
vect_loss: categorical_crossentropy

# Dropout options
dropout:
  flag: False
  percentage: 0.2

# Epochs
n_epochs: 200

# Batch size
batch_size: 15

# Patience
patience: 10

# Data
data_dir: /home/docker/data/Frames_dataset/linear_point_255_var_100000/linear_10_[None]_
#data_dir: /home/docker/data/Frames_dataset/linear_point_255_var_10000/linear_10_[None]_
batch_data: True #True or False
