# Version
version: 1

# Complexity: simple, complex, convLSTM, complex_convLSTM
complexity: complex

# Root to save the model
root: /home/docker/Models/

# Type of the net to train (NoRec, Rec)
net_type: NoRec

# Activation function
activation: relu
modeled_activation: tanh

# Loss function
func_loss: mean_squared_error
vect_loss: categorical_crossentropy
raw_frame_loss: categorical_crossentropy
modeled_frame_loss: mean_squared_error


# Dropout options
dropout:
  flag: False
  percentage: 0.2

# Epochs
n_epochs: 600

# Batch size
batch_size: 10

# Patience
patience: 10

# Data
data_dir: /home/docker/data/Frames_dataset/sinusoidal_point_255_var_2_100000_80_120/sinusoidal_10_[None]_
batch_data: False #True or False
data_model: modeled #raw or modeled
