# Test dataset path
data_path: /home/docker/data/Frames_dataset/sinusoidal_point_255_var_2_100000_80_120/sinusoidal_10_[None]_test/modeled_samples

# Model path
model_path: /home/docker/Models/NOREC/Frames_dataset/sinusoidal_point_255_var_2_100000_80_120_Modeled/simple/10_False_tanh_mean_squared_error_10.h5
