# Version
version: 1

# Root to save the model
root: /home/docker/2017-tfm-nuria-oyaga/Models/

# Type of the net to train (NoRec, Rec)
net_type: Rec

# Activation function
activation: relu

# Loss function
func_loss: mean_squared_error
vect_loss: categorical_crossentropy

# Dropout options
dropout:
  flag: False
  percentage: 0.2

# Epochs
n_epochs: 50

# Batch size
batch_size: 5

# Patience
patience: 10

# Data
#data_dir: /home/nuria/Documents/TFM/Functions_dataset/linear/linear_10_[None]_
#data_dir: /home/nuria/Documents/TFM/Vectors_dataset/URM/URM_10_[None]_
data_dir: /home/docker/2017-tfm-nuria-oyaga/Frames_dataset/URM_point_255/URM_10_[None]_
