# Version
version: 1

# Complexity: simple, complex, convLSTM
complexity: simple

# Root to save the model
root: /home/docker/Models/

# Type of the net to train (NoRec, Rec)
net_type: NoRec

# Activation function
activation: relu
modeled_activation: tanh

# Loss function
func_loss: mean_squared_error
vect_loss: categorical_crossentropy
raw_frame_loss: categorical_crossentropy
modeled_frame_loss: mean_squared_error


# Dropout options
dropout:
  flag: False
  percentage: 0.2

# Epochs
n_epochs: 600

# Batch size
batch_size: 15

# Patience
patience: 15

# Data
data_dir: /home/docker/data/Frames_dataset/parabolic_point_255_var_10000_80_120/parabolic_10_[None]_
batch_data: False #True or False
data_model: modeled #Raw or Modeled
