# Test dataset path
data_path: /home/docker/data/Frames_dataset/linear_point_255_var_10000_80_120/linear_10_[None]_test/modeled_samples

# Model path
model_path: /home/docker/Models/REC/Frames_dataset/linear_point_255_var_10000_80_120_Modeled/15_False_tanh_mean_squared_error_10.h5
